In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/bollywood.csv')
df

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [ ]:
df.isnull().sum()

movie    0
lead     0
dtype: int64

In [ ]:
df.sample()

                       movie           lead
241  Shaadi Mein Zaroor Aana  Rajkummar Rao

In [ ]:
df.iloc[5]

movie             Soni (film)
lead     Geetika Vidya Ohlyan
Name: 5, dtype: object

In [ ]:
df.shape

(1500, 2)

In [ ]:
df.describe()

                          movie          lead
count                      1500          1500
unique                     1497           566
top     Tanu Weds Manu: Returns  Akshay Kumar
freq                          2            48

In [ ]:
df.drop_duplicates().sum()

movie    Uri: The Surgical StrikeBattalion 609The Accid...
lead     Vicky KaushalVicky AhujaAnupam KherEmraan Hash...
dtype: object

In [ ]:
df.shape

(1500, 2)